# for one device, can be given like this:
hosts:
  - device: 10.209.16.204 
    username : demo
    passwd: demo123
tests:
  - test_exists.yml 
  - test_contains.yml
  - test_is_gt.yml

# use sqlite to store data 
sqlite:
  - store_in_sqlite: no
    check_from_sqlite: no
    database_name: jbb.db

# specify user and its details in yaml file to send mail
# mail: send_mail.yml