name: Pylint

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install pylint
        python3.7 -m pip install -r requirements.txt
        python3.7 -m pip install -r development.txt
        sudo python3.7 setup.py install

    - name: Analysing the code with pylint
      run: |
        find . -type f -name "*.py" | xargs pylint | grep .
    
    - name: Run black tool
      run: |
        python3.7 -m pip install -U black;
        black --check --exclude="docs|build|tests|samples|venv" .
    
    - name: Run unit tests
      run: |
        sudo python3.7 -m pip install -r requirements.txt
        sudo python3.7 -m pip install -r development.txt
        sudo python3.7 -m pip install junos-eznc
        nosetests -v --with-coverage --cover-package=jnpr.jsnapy --cover-inclusive -a tests/unit
